# Generated by Django 5.2.16 on 2026-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='belt',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10, verbose_name='status'),
        ),
    ]
