# Generated by Django 5.2.16 on 2026-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_belt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.PositiveIntegerField(error_messages={'unique': 'This Employee ID is already in use by another user.'}, unique=True, verbose_name='employee ID'),
        ),
    ]
