# Generated by Django 5.2.16 on 2026-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industries',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
