# Generated by Django 5.2.16 on 2026-07-10 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('project_name', models.CharField(max_length=255, verbose_name='project name')),
                ('division', models.CharField(blank=True, max_length=255, verbose_name='division')),
                ('scope', models.TextField(blank=True, verbose_name='scope')),
                ('lead_type', models.CharField(choices=[('BD', 'BD'), ('Mining', 'Mining')], default='BD', max_length=10, verbose_name='lead type')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Dropped', 'Dropped'), ('Hybernation', 'Hybernation'), ('Complete', 'Complete')], default='In Progress', max_length=20, verbose_name='status')),
                ('project_id', models.CharField(blank=True, default='', max_length=50, verbose_name='project ID')),
                ('project_id_base', models.CharField(blank=True, default='', max_length=50, verbose_name='project ID base')),
                ('extension', models.CharField(default='00', help_text='2-digit, zero-padded; increments each Task 16 closure.', max_length=2, verbose_name='extension')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='reference.country', verbose_name='country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('domain', models.ForeignKey(help_text="Called 'Domain' on the lead form, 'Area' in the workflow sheet.", on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='reference.area', verbose_name='domain')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='reference.industry', verbose_name='industry')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
