# Generated by Django 5.2.16 on 2026-07-10 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.CharField(choices=[('BD', 'BD'), ('Mining', 'Mining')], default='BD', max_length=10, verbose_name='type')),
                ('workflow', models.JSONField(default=dict, verbose_name='workflow definition')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'workflows',
                'ordering': ['type', '-status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.PositiveIntegerField(verbose_name='task no')),
                ('task_name', models.CharField(max_length=255, verbose_name='task name')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('hold', 'hold'), ('closed', 'closed')], default='open', max_length=10, verbose_name='status')),
                ('is_allocation_task', models.BooleanField(default=False, verbose_name='is allocation task')),
                ('extra_fields', models.JSONField(blank=True, default=dict, verbose_name='extra field values')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='opened at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('elapsed_time', models.DurationField(blank=True, null=True, verbose_name='elapsed time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=20, verbose_name='item key')),
                ('item_label', models.CharField(max_length=255, verbose_name='item label')),
                ('status', models.CharField(choices=[('not_started', 'not started'), ('inprogress', 'in progress'), ('complete', 'complete')], default='not_started', max_length=15, verbose_name='status')),
                ('remark', models.TextField(blank=True, verbose_name='remark')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='last edited at')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_checklist_items', to=settings.AUTH_USER_MODEL, verbose_name='last edited by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='leads.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'checklist item',
                'verbose_name_plural': 'checklist items',
                'ordering': ['id'],
            },
        ),
    ]
