# Generated by Django 5.2.16 on 2026-07-10 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_workflow_task_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='hold at')),
                ('unhold_at', models.DateTimeField(blank=True, null=True, verbose_name='unhold at')),
                ('hold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='hold by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='leads.lead', verbose_name='lead')),
                ('unhold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='unhold by')),
            ],
            options={
                'verbose_name': 'lead hold',
                'verbose_name_plural': 'lead holds',
                'ordering': ['-hold_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='hold at')),
                ('unhold_at', models.DateTimeField(blank=True, null=True, verbose_name='unhold at')),
                ('hold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='hold by')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='leads.task', verbose_name='task')),
                ('unhold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='unhold by')),
            ],
            options={
                'verbose_name': 'task hold',
                'verbose_name_plural': 'task holds',
                'ordering': ['-hold_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowTriggerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.PositiveIntegerField(help_text='The trigger task this rule controls (e.g. 2, 6, 11, 13, 15).', verbose_name='task no')),
                ('reference_task_no', models.PositiveIntegerField(help_text='The earlier task whose date field is the reference point.', verbose_name='reference task no')),
                ('reference_field_key', models.CharField(help_text='Field key on the reference task holding the date (e.g. expected_start_date).', max_length=100, verbose_name='reference field key')),
                ('offset_days', models.PositiveIntegerField(default=0, help_text='Days before the reference date the task opens. 0 = opens on the date itself.', verbose_name='offset days')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_configs', to='leads.workflow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'workflow trigger config',
                'verbose_name_plural': 'workflow trigger configs',
                'ordering': ['workflow', 'task_no'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'task_no'), name='uniq_trigger_per_workflow_task')],
            },
        ),
    ]
