# Generated by Django 5.2.16 on 2026-07-10 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadhold_taskhold_workflowtriggerconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('2HR', '2Hr Study & Presentation'), ('SNT', 'Solution Blueprint'), ('Implementation', 'Implementation'), ('Extension', 'Extension')], max_length=20, verbose_name='type')),
                ('remark', models.TextField(blank=True, verbose_name='remark')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Closed', 'Closed')], default='Pending', max_length=10, verbose_name='status')),
                ('man_power_required', models.PositiveIntegerField(default=0, help_text='Headcount captured from the triggering stage; over-allocation reference.', verbose_name='man power required')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('allocation_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to='leads.task', verbose_name='allocation task')),
                ('auditor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auditor 1')),
                ('auditor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auditor 2')),
                ('auditor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auditor 3')),
                ('auditor4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auditor 4')),
                ('execution_brown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='execution brown')),
                ('execution_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='execution red')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='leads.lead', verbose_name='lead')),
                ('project_member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 1')),
                ('project_member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 2')),
                ('project_member3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 3')),
                ('project_member4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 4')),
                ('project_member5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 5')),
                ('white', models.ForeignKey(blank=True, help_text='May be left blank — TBD is allowed (PRD §5.7).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='white')),
            ],
            options={
                'verbose_name': 'resource allocation',
                'verbose_name_plural': 'resource allocations',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_no', models.CharField(default='00', max_length=2, verbose_name='extension no')),
                ('project_id', models.CharField(max_length=50, verbose_name='project ID')),
                ('project_id_base', models.CharField(max_length=50, verbose_name='project ID base')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Extended', 'Extended'), ('Complete', 'Complete')], default='In Progress', max_length=15, verbose_name='status')),
                ('is_current', models.BooleanField(default=True, verbose_name='is current')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='generated at')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_project_details', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='leads.lead', verbose_name='lead')),
                ('resource_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_details', to='leads.resourceallocation', verbose_name='resource allocation')),
            ],
            options={
                'verbose_name': 'project details',
                'verbose_name_plural': 'project details',
                'ordering': ['lead', 'extension_no'],
            },
        ),
    ]
