# Generated by Django 5.2.16 on 2026-07-10 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_resourceallocation_projectdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('followup_date', models.DateField(help_text='Must not be a past date (§3).', verbose_name='follow-up date')),
                ('remark', models.TextField(blank=True, verbose_name='remark')),
                ('status', models.CharField(choices=[('open', 'open'), ('done', 'done')], default='open', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(help_text='An Employee-role user, or the Lead Manager themself.', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_followups', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_followups', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'follow-up',
                'verbose_name_plural': 'follow-ups',
                'ordering': ['status', 'followup_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FollowupUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followup_updates', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='leads.followup', verbose_name='follow-up')),
            ],
            options={
                'verbose_name': 'follow-up update',
                'verbose_name_plural': 'follow-up updates',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
