# Generated by Django 5.2.16 on 2026-07-10 18:07

import django.db.models.deletion
import leads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_followup_followupupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, verbose_name='type')),
                ('summary', models.CharField(max_length=255, verbose_name='summary')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'activity log entry',
                'verbose_name_plural': 'activity log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=leads.models.attachment_upload_path, verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.lead', verbose_name='lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lead_assigned', 'lead assigned'), ('task_opened', 'task opened'), ('task_reassigned', 'task reassigned'), ('followup', 'follow-up')], max_length=40, verbose_name='type')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
