# Generated by Django 5.2.16 on 2026-07-13, hand-ordered so the single-FK
# Execution-Brown/White values are preserved into the new multi-select fields
# before the old FK columns are dropped.

from django.conf import settings
from django.db import migrations, models


def copy_fk_to_m2m(apps, schema_editor):
    """Carry each row's single Execution-Brown / White into the new M2M sets."""
    RA = apps.get_model('leads', 'ResourceAllocation')
    for row in RA.objects.all():
        if row.execution_brown_id:
            row.execution_browns.add(row.execution_brown_id)
        if row.white_id:
            row.whites.add(row.white_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_activitylog_attachment_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add the new multi-select + split fields (old FKs still present).
        migrations.AddField(
            model_name='resourceallocation',
            name='execution_browns',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='execution browns'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='whites',
            field=models.ManyToManyField(blank=True, help_text='May be left empty — TBD is allowed (PRD §5.7).', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='whites'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='man_power_brown',
            field=models.PositiveIntegerField(default=0, verbose_name='man power required — brown'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='man_power_white',
            field=models.PositiveIntegerField(default=0, verbose_name='man power required — white'),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='man_power_required',
            field=models.PositiveIntegerField(default=0, help_text='Total headcount captured from the triggering stage (Brown + White).', verbose_name='man power required'),
        ),
        # 2. Move existing single-FK values into the M2M sets.
        migrations.RunPython(copy_fk_to_m2m, noop),
        # 3. Drop the now-superseded single FKs.
        migrations.RemoveField(
            model_name='resourceallocation',
            name='execution_brown',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='white',
        ),
    ]
