# Generated by Django 5.2.16 on 2026-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_resource_multiselect_manpower_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead_assigned', 'lead assigned'), ('task_opened', 'task opened'), ('task_reassigned', 'task reassigned'), ('followup', 'follow-up'), ('lead_held', 'lead put on hold'), ('task_held', 'task put on hold')], max_length=40, verbose_name='type'),
        ),
    ]
