# Generated by Django 5.2.16 on 2026-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_resource_brown_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhold',
            name='reason',
            field=models.TextField(blank=True, verbose_name='reason'),
        ),
        migrations.AddField(
            model_name='taskhold',
            name='reason',
            field=models.TextField(blank=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead_assigned', 'lead assigned'), ('task_opened', 'task opened'), ('task_reassigned', 'task reassigned'), ('task_completed', 'task completed'), ('followup', 'follow-up'), ('lead_held', 'lead put on hold'), ('task_held', 'task put on hold')], max_length=40, verbose_name='type'),
        ),
    ]
