# Generated by Django 5.2.16 on 2026-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_leadhold_reason_taskhold_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('hold', 'hold'), ('closed', 'closed'), ('skipped', 'skipped'), ('dropped', 'dropped')], default='open', max_length=10, verbose_name='status'),
        ),
    ]
