# Generated by Django 5.2.16 on 2026-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='drop_remark',
            field=models.TextField(blank=True, verbose_name='drop remark'),
        ),
        migrations.AddField(
            model_name='leadhold',
            name='unhold_reason',
            field=models.TextField(blank=True, verbose_name='unhold reason'),
        ),
        migrations.AddField(
            model_name='taskhold',
            name='unhold_reason',
            field=models.TextField(blank=True, verbose_name='unhold reason'),
        ),
    ]
