# Generated by Django 5.2.16 on 2026-07-16 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_drop_remark_leadhold_unhold_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceallocation',
            name='project_member10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 10'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='project_member6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 6'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='project_member7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 7'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='project_member8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 8'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='project_member9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='project member 9'),
        ),
    ]
