# Generated by Django 5.2.16 on 2026-07-21 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_resourceallocation_project_member10_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='short_closed',
            field=models.BooleanField(default=False, verbose_name='short closed'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='short_closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='short closed at'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='short_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='short closed by'),
        ),
        migrations.AddField(
            model_name='task',
            name='short_closed',
            field=models.BooleanField(default=False, verbose_name='short closed'),
        ),
    ]
