# Generated by Django 5.2.16 on 2026-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_projectdetails_short_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='short_close_remark',
            field=models.TextField(blank=True, verbose_name='short close remark'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Dropped', 'Dropped'), ('Hybernation', 'Hybernation'), ('Complete', 'Complete'), ('Short Closed', 'Short Closed')], default='In Progress', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Extended', 'Extended'), ('Complete', 'Complete'), ('Short Closed', 'Short Closed')], default='In Progress', max_length=15, verbose_name='status'),
        ),
    ]
