# Generated by Django 5.2.16 on 2026-07-26 17:50
#
# Phase R1 (v4.0/v17.0 rebuild): Lead schema change. The lead/task/etc. data was
# already cleared in 0016_reset_lead_data (decision D4) so this migration only
# alters structure — no back-mapping. All operations here are auto-reversible.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_reset_lead_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='country',
        ),
        migrations.AddField(
            model_name='lead',
            name='base_code',
            field=models.CharField(blank=True, help_text='Stable {AreaCode}{YY}{Seq}; generated at creation (R2).', max_length=50, null=True, unique=True, verbose_name='project base code'),
        ),
        migrations.AddField(
            model_name='lead',
            name='flow_of_tasks',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT (2HR → SnT → Proposal)'), ('2HR_PROPOSAL', '2HR → Project Proposal'), ('DIRECT_PROPOSAL', 'Direct Proposal'), ('SNT_PROPOSAL', 'SnT → Project Proposal')], max_length=20, verbose_name='flow of tasks'),
        ),
        migrations.AddField(
            model_name='lead',
            name='parent_lead',
            field=models.ForeignKey(blank=True, help_text='Set on a Mining-spawned lead (Task 21); NULL otherwise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mining_children', to='leads.lead', verbose_name='parent lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='type_of_project',
            field=models.CharField(blank=True, choices=[('Consulting Full Fledged', 'Consulting Full Fledged'), ('AMC', 'AMC'), ('Upgrade', 'Upgrade'), ('Vectorflow Lite', 'Vectorflow Lite'), ('Audit only', 'Audit only'), ('Consulting Lite + No software', 'Consulting Lite + No software')], max_length=40, verbose_name='type of project'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('BD', 'BD'), ('Extension', 'Extension'), ('Mining', 'Mining')], default='BD', max_length=10, verbose_name='lead type'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Hold', 'Hold'), ('Dropped', 'Dropped'), ('Completed', 'Completed')], default='In Progress', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.CharField(choices=[('BD', 'BD'), ('Extension', 'Extension'), ('Mining', 'Mining')], default='BD', max_length=10, verbose_name='type'),
        ),
    ]
