# Generated by Django 5.2.16 on 2026-07-26 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_lead_schema_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text='BD, 2HR, SnT, IM, E0/E1/…, M, or Closure (§4.4).', max_length=10, verbose_name='stage')),
                ('stage_start_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='stage start')),
                ('stage_end_dt', models.DateTimeField(blank=True, null=True, verbose_name='stage end')),
                ('status', models.CharField(choices=[('in_progress', 'in progress'), ('closed', 'closed'), ('skipped', 'skipped')], default='in_progress', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'lead stage',
                'verbose_name_plural': 'lead stages',
                'ordering': ['lead', 'stage_start_dt', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='leads.leadstage', verbose_name='stage'),
        ),
    ]
