# Generated by Django 5.2.16 on 2026-07-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_leadstage_task_stage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowtriggerconfig',
            name='uniq_trigger_per_workflow_task',
        ),
        migrations.AddField(
            model_name='task',
            name='is_finance_gate',
            field=models.BooleanField(default=False, verbose_name='is finance gate'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_hanging_task',
            field=models.BooleanField(default=False, verbose_name='is hanging task'),
        ),
        migrations.AddField(
            model_name='task',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0, verbose_name='reopened count'),
        ),
        migrations.AddField(
            model_name='workflowtriggerconfig',
            name='condition_field_key',
            field=models.CharField(blank=True, default='', help_text='Optional: numeric field on the reference task this rule is gated on (e.g. period_months).', max_length=100, verbose_name='condition field key'),
        ),
        migrations.AddField(
            model_name='workflowtriggerconfig',
            name='condition_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This rule applies only when the condition field is ≤ this value.', max_digits=12, null=True, verbose_name='condition max'),
        ),
        migrations.AlterField(
            model_name='workflowtriggerconfig',
            name='offset_days',
            field=models.IntegerField(default=0, help_text='Signed. The task opens on reference_date − offset_days: a positive value opens it that many days BEFORE the reference date, a negative value that many days AFTER (e.g. Task 21 opens months after the engagement start). 0 = opens on the date itself.', verbose_name='offset days'),
        ),
        migrations.AddConstraint(
            model_name='workflowtriggerconfig',
            constraint=models.UniqueConstraint(fields=('workflow', 'task_no', 'condition_field_key'), name='uniq_trigger_per_workflow_task_condition'),
        ),
    ]
