# Generated by Django 5.2.16 on 2026-07-27 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_task_flags_trigger_conditions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceallocation',
            options={'ordering': ['-allocated_on', '-id'], 'verbose_name': 'resource allocation', 'verbose_name_plural': 'resource allocations'},
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='resource_allocation',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='auditor1',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='auditor2',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='auditor3',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='auditor4',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='execution_brown',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='execution_red',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='man_power_brown',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='man_power_white',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member1',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member10',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member2',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member3',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member4',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member5',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member6',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member7',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member8',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='project_member9',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='resourceallocation',
            name='whites',
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='allocated_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='allocated on'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='is_tbd',
            field=models.BooleanField(default=False, help_text='White only — a slot may be left to-be-decided (PRD §5.7).', verbose_name='is TBD'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='released_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='released on'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='Set when this row replaces a reassigned one — the replaced row is set to released (§4.7).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='leads.resourceallocation', verbose_name='replaces'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='slot',
            field=models.CharField(choices=[('execution_red', 'Execution Red'), ('execution_brown', 'Execution Brown'), ('white', 'White'), ('auditor_1', 'Auditor 1'), ('auditor_2', 'Auditor 2')], default='execution_red', max_length=20, verbose_name='slot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='stage',
            field=models.ForeignKey(blank=True, help_text="Which stage this slot's occupant is working (§4.7).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to='leads.leadstage', verbose_name='stage'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='lead',
            field=models.ForeignKey(help_text='Denormalized for reporting (§4.7).', on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='leads.lead', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='man_power_required',
            field=models.PositiveIntegerField(default=0, help_text="Headcount required for this slot, captured from the triggering stage's manpower fields — feeds the over/under-allocation indicators.", verbose_name='man power required'),
        ),
        migrations.AlterField(
            model_name='resourceallocation',
            name='status',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('released', 'Released')], default='allocated', max_length=10, verbose_name='status'),
        ),
    ]
