# Generated by Django 5.2.16 on 2026-07-27 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_resourceallocation_append_only_rebuild'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdetails',
            options={'ordering': ['lead', 'generated_at', 'id'], 'verbose_name': 'project details', 'verbose_name_plural': 'project details'},
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='extension_no',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='project_id_base',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='short_close_remark',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='short_closed',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='short_closed_at',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='short_closed_by',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='short_close_remark',
            field=models.TextField(blank=True, verbose_name='short close remark'),
        ),
        migrations.AddField(
            model_name='lead',
            name='short_closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='short closed at'),
        ),
        migrations.AddField(
            model_name='lead',
            name='short_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='short closed by'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='fixed fee'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='The IM/E{n} cycle this commercial record belongs to (§4.8).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_details', to='leads.leadstage', verbose_name='stage'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='variable_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='variable fee'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_id',
            field=models.CharField(help_text='The derived display Project ID, snapshotted at generation time.', max_length=50, verbose_name='project ID'),
        ),
    ]
