# Generated by Django 5.2.16 on 2026-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_r6_mining_extension_project_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='base_code',
            field=models.CharField(blank=True, help_text='Stable {AreaCode}{YY}{Seq}; generated at creation (R2); shared with Mining children (R6).', max_length=50, null=True, verbose_name='project base code'),
        ),
    ]
