# Generated by Django 5.2.16 on 2026-07-27 11:05
#
# Meeting decision 2026-07-27: give the five core tables their clean raw names
# (lead / lead_stage / task_details / project_details / resource_table) and add
# the report/dashboard columns discussed — lead lifecycle span + stable
# project_id, per-cycle `project` stage-code label, and a denormalized resource
# `names`. Existing rows are backfilled so the columns are populated immediately.

import django.utils.timezone
from django.db import migrations, models

_MINING_STAGE = "M"
_MINING_LEAD_TYPE = "Mining"
_TERMINAL_STATUSES = ("Completed", "Dropped")


def backfill_report_columns(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    ProjectDetails = apps.get_model("leads", "ProjectDetails")
    ResourceAllocation = apps.get_model("leads", "ResourceAllocation")

    for lead in Lead.objects.iterator():
        # lead_start_dt = creation; lead_end_dt = updated_at if already terminal.
        lead.lead_start_dt = lead.created_at
        if lead.status in _TERMINAL_STATUSES and lead.lead_end_dt is None:
            lead.lead_end_dt = lead.updated_at
        # Stable lead-level project_id: base_code (+ -M for Mining), no suffix.
        if lead.base_code:
            lead.project_id = (
                f"{lead.base_code}-M" if lead.lead_type == _MINING_LEAD_TYPE else lead.base_code
            )
        lead.save(update_fields=["lead_start_dt", "lead_end_dt", "project_id"])

    # project = the cycle's stage code (copy of stage.stage).
    for pd in ProjectDetails.objects.select_related("stage").iterator():
        pd.project = pd.stage.stage if pd.stage_id else ""
        pd.save(update_fields=["project"])

    # names = the occupant's display name snapshot (or "TBD"/"").
    for row in ResourceAllocation.objects.select_related("user").iterator():
        if row.user_id:
            row.names = row.user.name
        else:
            row.names = "TBD" if row.is_tbd else ""
        row.save(update_fields=["names"])


def noop_reverse(apps, schema_editor):
    """Reverse drops the added columns; nothing to restore."""


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_stored_project_id_and_field_renames'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_end_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='lead end'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_start_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='lead start'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project',
            field=models.CharField(blank=True, default='', help_text='Stage code for this cycle (IM / E{n} / M); copy of stage.stage.', max_length=10, verbose_name='project'),
        ),
        migrations.AddField(
            model_name='resourceallocation',
            name='names',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='names'),
        ),
        migrations.AlterModelTable(
            name='lead',
            table='lead',
        ),
        migrations.AlterModelTable(
            name='leadstage',
            table='lead_stage',
        ),
        migrations.AlterModelTable(
            name='projectdetails',
            table='project_details',
        ),
        migrations.AlterModelTable(
            name='resourceallocation',
            table='resource_table',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task_details',
        ),
        migrations.RunPython(backfill_report_columns, noop_reverse),
    ]
