# Generated by Django 5.2.16 on 2026-08-03 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_retire_tbd_allocations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstage',
            name='stage',
            field=models.CharField(help_text='BD, 2HR, SnT, IM, E1/E2/…, M, or Closure (§4.4).', max_length=10, verbose_name='stage'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notification_user_feed_idx'),
        ),
    ]
