# Generated by Django 5.2.16 on 2026-08-05 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_notification_feed_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead_assigned', 'lead assigned'), ('task_opened', 'task opened'), ('task_reassigned', 'task reassigned'), ('task_completed', 'task completed'), ('followup', 'follow-up'), ('lead_comment', 'lead trail comment'), ('lead_held', 'lead put on hold'), ('task_held', 'task put on hold')], max_length=40, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, default='', help_text="Display snapshot of the lead's Project ID when this row was created; not a join key (§13).", max_length=50, verbose_name='project ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leads.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'lead trail comment',
                'verbose_name_plural': 'lead trail',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
