# Generated by Django 5.2.16 on 2026-08-05 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_alter_notification_type_leadcomment'),
        ('reference', '0002_area_status_country_status_industry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-created_at', '-id'], name='lead_list_order_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstage',
            index=models.Index(fields=['lead', 'status', '-stage_start_dt'], name='lead_stage_current_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lead', 'status', 'task_no'], name='task_lead_status_no_idx'),
        ),
    ]
